global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexus-ai-gateway'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nexus-ai-auth'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nexus-ai-task'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nexus-ai-ai'
    static_configs:
      - targets: ['host.docker.internal:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis-debian'
    static_configs:
      - targets: ['redis-exporter-debian:9121']

  - job_name: 'redis-alpine'
    static_configs:
      - targets: ['redis-exporter-alpine:9121']


  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']